config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  unauthenticated :user do
    root to: 'users#index'
  end

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  resources :groups
  resources :expenses
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Expense, author: user
    can :manage, Group, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :groups, dependent: :destroy

  validates :name, :amount, presence: true, length: { maximum: 255 }
  validates :amount, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
  has_one_attached :image

  def total_amount
    expenses.sum('amount')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :name, :email, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  load_and_authorize_resource

  def index
    redirect_to groups_url
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    @expense.author = current_user

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense.groups.first, notice: 'Expense was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    flash[:success] = 'Expense was successfully deleted.'
    redirect_to root_path
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource

  def index
    @groups = current_user.groups.order(:name)
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @expenses = @group.expenses.order('created_at DESC')
  end

  def create
    @group = current_user.groups.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to root_path, notice: 'Category was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Category was successfully destroyed!.' }
    end
  end

  private

  def set_group
    @group = Group.includes(:expenses).find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_expense.html.erb
<div class="container card mb-4">
	<div class="p-4">
		<div class="d-flex justify-content-between flex-column">
			<h5><%= expense.name %></h5>
			<small>$<%= expense.amount.round(2) %></small>
			<%= button_to "Delete", expense_path(expense), :method => :delete, :class => "btn btn-danger btn-sm"%>
		</div>
		<small class='text-muted'><%= expense.created_at.strftime("%d %b %Y") %></small>
	</div>
</div>

app/views/expenses/_form.html.erb
  <%= form_with(model: expense) do |form| %>
    <div>
      <h5 class='text-center display-6'>Add new transaction</h5>
    </div>
    <%= render "devise/shared/error_messages", resource: expense %>
    <div class="container">
      <%= form.text_field :name, autofocus: true, placeholder: "Name", class: "form-control m-2", required: true %>
      <%= form.number_field :amount, placeholder: "Amount", class: "form-control  m-2", required: true, step: 'any' %>
      <%= form.collection_select :group_ids, current_user.groups.order(:name), :id, :name, {}, { class: "form-select  m-2", multiple: true, required: true } %>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
      <%= form.submit "Save", class: "btn btn-success" %>
    </div>
  <% end %>

app/views/expenses/_index.html.erb
<div class="container">
<%= render @expenses %>
</div>

app/views/expenses/new.html.erb
<%= render 'form', expense: @expense %>

app/views/groups/_categories.html.erb
<% if @groups.any?%>
<% @groups.each do |group| %>
  <div class="card mb-3 p-2 container">
    <div class="row">
      <div class="col">
        <%=image_tag group.image%>
      </div>
      <div class="col d-flex justify-content-evenly flex-column">
          <h5 class="card-title "><%= link_to group.name, group_path(group), class: "text-decoration-none" %></h5>
          <p class="card-text"><small class="text-muted fs-6"><%= group.created_at.strftime("%d-%b-%Y")%></small></p>
      </div>
      <div class="col d-flex justify-content-evenly flex-column">
        <p> $<%= group.expenses.sum(:amount)%></p>
        <%if can? :destroy, group %>
          <%= button_to "Delete", group_path(group), method: :delete, class:"btn btn-danger btn-sm" %>
        <%end%>
      </div>
    </div>
  </div>
<%end%>
<%else%>
  <p class="p-2 m-2 h3">There is no category added!!!</p>
<%end%>

app/views/groups/_form.html.erb
<%= form_with(model: @group) do |form| %>
  <div class="container">

      <div class='pb-2'>
        <h5 class='text-center display-6'>Add a new category </h5>
      </div>
    <div class="m-3">
      <%= form.text_field :name, autofocus: true, placeholder: "Name", class: "form-control", required: true %>
    </div>
    <div class="m-3">
      <%= form.file_field :image, placeholder: "Image", class: "form-control", required: true %>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
      <%= form.submit "Save", class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/groups/index.html.erb
<div class="container">
  <%= render 'categories' %>
</div>

<footer class="footer">
  <div class="d-grid gap-2">
    <%= link_to "Add a new category", new_group_path, class: "btn btn-success border-radius-none" %>
  </div>
</footer>

app/views/groups/new.html.erb
<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<div class="containers">
  <h5 class='text-center display-6'>TRANSACTION</h5>
  <div class="container p-4 pd-0 d-flex justify-content-between">
		<h5 class="fw-bold">Total Amount:</h5>
		<p class="fw-bold">$<%= @group.total_amount.round(2) %></p>
  </div>
  <div class="p-4 pt-0">
    <%=image_tag @group.image, class: 'img-thumbnail ratio ratio-21x9' %>
    <p class="text-muted text-end pt-2"><%= @group.name %></p>
  </div>
</div>
  <div class="divider mb-2"></div>
	  <%= render 'expenses/index', locals: { expenses: @expenses } %>
  </div>

<footer class="footer">
  <div class="d-grid gap-2">
    <%= link_to "Add new transaction", new_expense_path, class: "btn btn-success border-radius-none" %>
  </div>
</footer>

app/views/layouts/_alerts.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<% if notice %>
  <div class="alert alert-success d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
    <%= notice %>
  </div>
<% elsif alert %>
  <div class="alert alert-success d-flex align-items-center" role="alert">
    <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Main CSS -->
    <link rel="stylesheet" href="../assets/stylesheets/application.css">
    
    <title>BudgetApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "navbar/navbar" %>
    <br>
    <div class="container">
      <%= render 'layouts/alerts' %>
    </div>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <% if root_path != request.path %>
      <%= link_to root_path do %>
        <button class='btn' style='width: 70px;'>
          <%= image_tag 'arrow.svg', class: "navbar-brand"  %>
        </button>
      <% end %>    
    <% end %>
    
    
    <a class="navbar-brand" href="#">BudgeT App</a>
    
    <% if user_signed_in? %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
    <% end %>
    
    <%# <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%# <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li> %>
        <%# <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li> %>
      </ul>
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<div class="background">


      <div class="container">
        <div>
          <h1 class="title text-center display-4 text-muted">Budget<small style="color: #24a0ed;">App</small></h1>
        </div>
        
        <div class="btn-group padding centered">
          <%= link_to 'Log in', user_session_path, class: 'btn btn-info text-nowrap'%>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-light text-nowrap'%>
        </div>
      
    </div>
   <span></span>
   <span></span>
   <span></span>
   <span></span>
   <span></span>
   <span></span>
   <span></span>
</div>